// Diccionarios básicos para la validación automática.
// IMPORTANTE: una palabra que NO esté aquí no se elimina; solo queda marcada
// "por revisar" y los jugadores pueden impugnarla. Puedes ampliar estas listas libremente.

const w = (s) => s.split(',').map((x) => x.trim()).filter(Boolean);

const DICTIONARIES = {
  nombre: w(`
Aarón,Abel,Abigail,Abril,Adán,Adela,Adolfo,Adrián,Adriana,Agustín,Agustina,Aída,Aitana,Alan,Alba,Alberto,Alejandra,Alejandro,Alessandra,Alessandro,Alexis,Alfonso,Alfredo,Alicia,Alma,Alonso,Álvaro,Amanda,Amelia,Ana,Anabel,Andrea,Andrés,Ángel,Ángela,Ángeles,Angélica,Aníbal,Antonella,Antonia,Antonio,Araceli,Ariana,Ariel,Armando,Arturo,Augusto,Aurora,Axel,
Beatriz,Belén,Benjamín,Bernardo,Berta,Blanca,Brenda,Bruno,Brayan,Bryan,
Camila,Camilo,Candela,Carla,Carlos,Carmen,Carolina,Catalina,Cecilia,César,Cristian,Christian,Cintia,Clara,Claudia,Claudio,Constanza,Cristina,Cristóbal,
Dafne,Daniel,Daniela,Danna,Darío,David,Débora,Delia,Denis,Diana,Diego,Dolores,Domingo,Dora,Dulce,
Edgar,Eduardo,Elena,Elías,Elisa,Eliana,Elizabeth,Elsa,Elvira,Emilia,Emiliano,Emilio,Emma,Enrique,Erick,Erika,Ernesto,Esteban,Estefanía,Estela,Ester,Esther,Eugenia,Eva,Evelyn,Ezequiel,
Fabiola,Fabián,Fabio,Facundo,Federico,Felipe,Fernanda,Fernando,Fidel,Flor,Florencia,Francisca,Francisco,Franco,Gabriel,Gabriela,Gael,Gerardo,Germán,Gilberto,Gisela,Gloria,Gonzalo,Graciela,Gregorio,Guadalupe,Guillermo,Gustavo,
Héctor,Helena,Hernán,Hilda,Hugo,Humberto,
Ian,Ignacio,Inés,Irene,Iris,Isaac,Isabel,Isabella,Ismael,Iván,Ivonne,
Jacinto,Jaime,Javier,Jazmín,Jesús,Jessica,Jimena,Joaquín,Johan,Jonathan,Jorge,José,Josefina,Josué,Juan,Juana,Julia,Julián,Juliana,Julio,Jhon,Jayr,
Karen,Karina,Karla,Katherine,Kevin,
Laura,Leandro,Leonardo,Leonel,Leticia,Lidia,Liliana,Lorena,Lorenzo,Lucas,Lucía,Luciana,Luciano,Lucio,Luis,Luisa,Luna,Lourdes,
Macarena,Magdalena,Manuel,Manuela,Marcela,Marcelo,Marcia,Marco,Marcos,Margarita,María,Mariana,Mariano,Maribel,Marina,Mario,Marisol,Marta,Martha,Martín,Martina,Mateo,Matías,Mauricio,Máximo,Melisa,Mercedes,Micaela,Miguel,Milagros,Mirtha,Mónica,Moisés,
Nadia,Natalia,Nathaly,Nelson,Néstor,Nicolás,Nicole,Noelia,Norma,Nora,
Octavio,Olga,Olivia,Omar,Óscar,Oswaldo,
Pablo,Paola,Patricia,Patricio,Paula,Paulina,Pedro,Pilar,Priscila,
Rafael,Ramiro,Ramón,Raquel,Raúl,Rebeca,Renato,Ricardo,Roberto,Rocío,Rodrigo,Rogelio,Rolando,Romina,Rosa,Rosario,Rubén,Ruth,
Salvador,Samanta,Samuel,Sandra,Santiago,Santino,Sara,Sebastián,Sergio,Silvia,Simón,Sofía,Soledad,Sonia,Susana,
Tamara,Teresa,Tatiana,Tomás,
Úrsula,Ulises,Valentín,Valentina,Valeria,Vanesa,Verónica,Vicente,Víctor,Victoria,Virginia,Viviana,
Walter,Wilson,Ximena,Xavier,Yolanda,Yesenia,Zoe,Zulema
`),
  apellido: w(`
Acosta,Aguilar,Aguirre,Alarcón,Álvarez,Arias,Ayala,Benítez,Bravo,Bustamante,Cabrera,Calderón,Campos,Cárdenas,Carrasco,Castillo,Castro,Chávez,Contreras,Córdova,Cortés,Cruz,Delgado,Díaz,Domínguez,Escobar,Espinoza,Estrada,Fernández,Figueroa,Flores,Fuentes,Gallardo,Gálvez,García,Gil,Gómez,González,Guerrero,Gutiérrez,Guzmán,Hernández,Herrera,Huamán,Ibáñez,Iglesias,Jiménez,Juárez,Lara,León,López,Lozano,Luna,Martínez,Medina,Mejía,Méndez,Mendoza,Miranda,Molina,Montes,Mora,Morales,Moreno,Muñoz,Navarro,Núñez,Ortega,Ortiz,Pacheco,Paredes,Peralta,Pérez,Ponce,Quispe,Quiroz,Ramírez,Ramos,Reyes,Ríos,Rivera,Rodríguez,Rojas,Romero,Rosales,Rubio,Ruiz,Salas,Salazar,Sánchez,Sandoval,Santos,Silva,Soto,Suárez,Tapia,Torres,Valdez,Valencia,Vargas,Vásquez,Vázquez,Vega,Velásquez,Vera,Villanueva,Zamora,Zapata,Zúñiga,
Abad,Abarca,Acevedo,Alcántara,Alfaro,Almeida,Alva,Andrade,Aponte,Aragón,Araujo,Arce,Arévalo,Armas,Ávila,Baca,Barrios,Becerra,Beltrán,Blanco,Bonilla,Caballero,Cáceres,Camacho,Cano,Carbajal,Carrillo,Casas,Cervantes,Cisneros,Colina,Correa,Cuadros,Cueva,Dávila,Del Pino,Durán,Echevarría,Espinosa,Farfán,Ferrer,Gamarra,Garay,Garrido,Guevara,Hidalgo,Huerta,Ibarra,Infante,Jara,Lazo,Linares,Llanos,Lozada,Maldonado,Manrique,Marín,Márquez,Meza,Montoya,Nieto,Ochoa,Olivares,Olivera,Orellana,Osorio,Palacios,Palomino,Pardo,Peña,Pinto,Prado,Quintana,Quiñones,Quiroga,Rengifo,Robles,Rosas,Salinas,Saavedra,Segura,Serrano,Solís,Tello,Toledo,Trujillo,Ugarte,Urbina,Uribe,Valle,Vallejo,Velarde,Vidal,Villa,Villalobos,Yáñez,Yupanqui,Zavala,Zegarra
`),
  animal: w(`
abeja,águila,alacrán,albatros,alce,alpaca,anaconda,anguila,antílope,araña,ardilla,armadillo,asno,atún,avestruz,avispa,ballena,búfalo,búho,burro,caballo,cabra,cacatúa,caimán,calamar,camaleón,camarón,camello,canario,cangrejo,canguro,caracol,castor,cebra,cerdo,chancho,chimpancé,chinchilla,ciervo,cigüeña,cisne,cobra,cocodrilo,codorniz,colibrí,comadreja,cóndor,conejo,coyote,cucaracha,cuervo,cuy,delfín,dingo,dromedario,elefante,erizo,escarabajo,escorpión,foca,flamenco,gacela,gallina,gallo,ganso,garza,gato,gaviota,gorila,gorrión,grillo,guacamayo,guanaco,guepardo,gusano,halcón,hámster,hiena,hipopótamo,hormiga,hurón,iguana,impala,jabalí,jaguar,jirafa,koala,lagartija,lagarto,langosta,lechuza,león,leopardo,liebre,llama,lobo,loro,lombriz,luciérnaga,mamut,manatí,mandril,mantarraya,mapache,mariposa,mariquita,medusa,mono,mosca,mosquito,murciélago,mula,nutria,ñandú,ñu,orangután,orca,oruga,oso,ostra,oveja,paloma,pantera,pato,pavo,pelícano,perdiz,perezoso,perico,perro,pez,pingüino,piraña,pollo,puercoespín,pulpo,puma,quetzal,rana,rata,ratón,reno,rinoceronte,ruiseñor,salamandra,salmón,saltamontes,sapo,sardina,serpiente,suricata,tapir,tarántula,tejón,tiburón,tigre,topo,toro,tortuga,trucha,tucán,urraca,vaca,venado,víbora,vicuña,vizcacha,yak,yegua,zancudo,zarigüeya,zorro,zorrillo,ornitorrinco,oso hormiguero,oso panda,panda,koi,kiwi,krill,jirafa,jilguero,golondrina,gamba,ganso,erizo de mar,estrella de mar,caballito de mar,lince,lémur,marmota,morsa,nutria,ocelote,okapi,pájaro,paujil,petirrojo,pez espada,pez payaso,raya,sapo,sepia,tilapia,termita,uakari,urubú,vampiro,yacaré,yaguareté,zebra,zorzal,boa,bisonte,bagre,anchoveta,alpaca,camarón,chinche,cucaracha,ganso,huemul,hurón,ibis,ibex,iguana
`),
  color: w(`
amarillo,ámbar,añil,aguamarina,albaricoque,azul,azul marino,azul cielo,beige,bermellón,blanco,borgoña,bronce,burdeos,café,caoba,canela,carmesí,carmín,celeste,cereza,champán,chocolate,cian,ciruela,cobre,coral,crema,dorado,escarlata,esmeralda,fucsia,granate,gris,grafito,guinda,hueso,índigo,jade,lavanda,lila,lima,magenta,malva,marfil,marrón,menta,miel,morado,mostaza,naranja,anaranjado,negro,nácar,ocre,oliva,oro,palo rosa,perla,plata,plateado,púrpura,rojo,rosa,rosado,rubí,salmón,sepia,siena,terracota,turquesa,ultramarino,uva,verde,verde limón,verde oliva,vino,violeta,zafiro,kaki,caqui,khaki,jaspe,lacre,ladrillo,fresa,frambuesa,durazno,damasco,berenjena,arena,avellana,amatista,ébano,cobalto,celadón,topacio,tostado,tabaco,zanahoria,blanco hueso,nogal,ónix,obsidiana,pistacho,rojo vino,rosa chicle,aguacate,xantico,xanadu
`),
  fruta: w(`
aceituna,acerola,aguacate,albaricoque,anona,arándano,aguaymanto,banana,banano,breva,cacao,caqui,carambola,cereza,chabacano,chirimoya,ciruela,coco,cocona,dátil,durazno,damasco,frambuesa,fresa,frutilla,granada,granadilla,grosella,guanábana,guayaba,guinda,higo,kiwi,kaki,kumquat,lima,limón,lúcuma,lichi,litchi,mamey,mandarina,mango,mangostán,manzana,maracuyá,melocotón,melón,membrillo,mora,naranja,nectarina,níspero,noni,papaya,pera,pepino dulce,pitahaya,piña,plátano,pomelo,quinoto,rambután,sandía,tamarindo,tangelo,tangerina,tomate de árbol,toronja,tuna,ugli,uva,uva verde,uva roja,yaca,zapote,zarzamora,camu camu,carambola,ciruelo,feijoa,jaca,jobo,maracuya,mangaba,mamón,nance,olivo,pacay,pepino,physalis,uchuva,umbu,ume,vainilla,yuzu,zarzaparrilla,arazá,borojó,caimito,copoazú,huito,ilama,icaco,jabuticaba,ackee
`),
  verdura: w(`
acelga,achicoria,ají,ajo,alcachofa,alcaparra,apio,arveja,berenjena,berro,betarraga,brócoli,brécol,calabacín,calabaza,camote,cebolla,cebollín,chalota,champiñón,chile,choclo,col,coles de bruselas,coliflor,colinabo,culantro,endibia,eneldo,escarola,espárrago,espinaca,frijol,garbanzo,guisante,haba,hinojo,hongo,jengibre,jícama,judía,kale,lechuga,lenteja,maíz,mostaza,nabo,ñame,ñuño,okra,olluco,oca,papa,patata,pepinillo,pepino,perejil,pimiento,pimentón,poro,puerro,rábano,remolacha,repollo,rúcula,tomate,vainita,yuca,zanahoria,zapallo,zucchini,apio nabo,arúgula,albahaca,quinua,quinoa,kión,jalapeño,habichuela,loche,mashua,rocoto,uchucuta,trigo,tomatillo,taro,soya,soja,setas,seta,orégano,menta,maca,lechuga romana,huacatay,granos,frejol,ejote,daikon,cilantro,col rizada,camote,berza,batata,arracacha,acelga,yacón,xoconostle,wasabi,vegetal,vainita,ulluco
`),
  pais: w(`
Afganistán,Albania,Alemania,Andorra,Angola,Antigua y Barbuda,Arabia Saudita,Argelia,Argentina,Armenia,Australia,Austria,Azerbaiyán,Bahamas,Bangladés,Barbados,Baréin,Bélgica,Belice,Benín,Bielorrusia,Birmania,Bolivia,Bosnia,Botsuana,Brasil,Brunéi,Bulgaria,Burkina Faso,Burundi,Bután,Cabo Verde,Camboya,Camerún,Canadá,Catar,Chad,Chile,China,Chipre,Colombia,Comoras,Congo,Corea,Corea del Norte,Corea del Sur,Costa de Marfil,Costa Rica,Croacia,Cuba,Dinamarca,Dominica,Ecuador,Egipto,El Salvador,Emiratos Árabes Unidos,Eritrea,Eslovaquia,Eslovenia,España,Estados Unidos,Estonia,Esuatini,Etiopía,Filipinas,Finlandia,Fiyi,Francia,Gabón,Gambia,Georgia,Ghana,Granada,Grecia,Guatemala,Guinea,Guinea Ecuatorial,Guinea-Bisáu,Guyana,Haití,Honduras,Hungría,India,Indonesia,Irak,Irán,Irlanda,Islandia,Islas Marshall,Islas Salomón,Israel,Italia,Jamaica,Japón,Jordania,Kazajistán,Kenia,Kirguistán,Kiribati,Kuwait,Laos,Lesoto,Letonia,Líbano,Liberia,Libia,Liechtenstein,Lituania,Luxemburgo,Macedonia,Madagascar,Malasia,Malaui,Maldivas,Malí,Malta,Marruecos,Mauricio,Mauritania,México,Micronesia,Moldavia,Mónaco,Mongolia,Montenegro,Mozambique,Namibia,Nauru,Nepal,Nicaragua,Níger,Nigeria,Noruega,Nueva Zelanda,Omán,Países Bajos,Holanda,Pakistán,Palaos,Palestina,Panamá,Papúa Nueva Guinea,Paraguay,Perú,Polonia,Portugal,Reino Unido,Inglaterra,Escocia,Gales,República Checa,Chequia,República Dominicana,Ruanda,Rumania,Rusia,Samoa,San Marino,Santa Lucía,Senegal,Serbia,Seychelles,Sierra Leona,Singapur,Siria,Somalia,Sri Lanka,Sudáfrica,Sudán,Suecia,Suiza,Surinam,Tailandia,Taiwán,Tanzania,Tayikistán,Timor Oriental,Togo,Tonga,Trinidad y Tobago,Túnez,Turkmenistán,Turquía,Tuvalu,Ucrania,Uganda,Uruguay,Uzbekistán,Vanuatu,Vaticano,Venezuela,Vietnam,Yemen,Yibuti,Zambia,Zimbabue,USA,EEUU,Puerto Rico,Groenlandia,Kosovo
`),
  ciudad: w(`
Lima,Arequipa,Trujillo,Chiclayo,Piura,Iquitos,Cusco,Cuzco,Huancayo,Chimbote,Tacna,Ica,Juliaca,Puno,Cajamarca,Pucallpa,Ayacucho,Huánuco,Tumbes,Moquegua,Chincha,Pisco,Nazca,Tarapoto,Huaraz,Sullana,Talara,Paita,Abancay,Huacho,Huaral,Barranca,Cañete,Ilo,Jaén,Moyobamba,Puerto Maldonado,Chachapoyas,Cerro de Pasco,Tingo María,Andahuaylas,Lambayeque,Ferreñafe,Mollendo,Camaná,Yurimaguas,Bagua,Oxapampa,Huancavelica,Callao,Miraflores,Olmos,Motupe,Casma,Huarmey,Supe,Paramonga,Chepén,Pacasmayo,Virú,Chao,Sechura,Catacaos,
Madrid,Barcelona,Valencia,Sevilla,Málaga,Bilbao,Zaragoza,Granada,Toledo,Salamanca,Murcia,Vigo,Alicante,Córdoba,Palma,París,Lyon,Marsella,Niza,Burdeos,Londres,Liverpool,Manchester,Edimburgo,Dublín,Roma,Milán,Nápoles,Venecia,Florencia,Turín,Génova,Berlín,Múnich,Hamburgo,Colonia,Fráncfort,Viena,Zúrich,Ginebra,Berna,Bruselas,Ámsterdam,Rotterdam,Lisboa,Oporto,Atenas,Estambul,Moscú,Kiev,Varsovia,Praga,Budapest,Oslo,Estocolmo,Copenhague,Helsinki,
Nueva York,Los Ángeles,Chicago,Miami,Houston,Dallas,Boston,Washington,San Francisco,Seattle,Las Vegas,Orlando,Atlanta,Denver,Filadelfia,Detroit,Toronto,Montreal,Vancouver,Ottawa,
Ciudad de México,Guadalajara,Monterrey,Cancún,Tijuana,Puebla,Acapulco,Mérida,Oaxaca,Guatemala,Tegucigalpa,San Salvador,Managua,San José,Panamá,La Habana,Santo Domingo,San Juan,Caracas,Maracaibo,Valencia,Bogotá,Medellín,Cali,Cartagena,Barranquilla,Quito,Guayaquil,Cuenca,La Paz,Santa Cruz,Cochabamba,Sucre,Potosí,Oruro,Santiago,Valparaíso,Viña del Mar,Antofagasta,Arica,Iquique,Concepción,Temuco,Punta Arenas,Buenos Aires,Rosario,Mendoza,Mar del Plata,Salta,Ushuaia,Montevideo,Punta del Este,Asunción,Encarnación,Río de Janeiro,São Paulo,Sao Paulo,Brasilia,Salvador,Recife,Fortaleza,Manaos,Belém,Curitiba,Porto Alegre,
Tokio,Osaka,Kioto,Pekín,Beijing,Shanghái,Hong Kong,Seúl,Bangkok,Singapur,Manila,Yakarta,Hanói,Delhi,Nueva Delhi,Bombay,Mumbai,Calcuta,Dubái,Abu Dabi,Doha,Riad,Jerusalén,Tel Aviv,Beirut,Teherán,Bagdad,El Cairo,Alejandría,Casablanca,Marrakech,Rabat,Túnez,Argel,Nairobi,Lagos,Johannesburgo,Ciudad del Cabo,Sídney,Melbourne,Brisbane,Perth,Auckland,Wellington,Kabul,Karachi,Lahore,Islamabad,Daca,Katmandú,Ulán Bator,Taipéi,Kuala Lumpur,Yokohama,Nagoya,Vladivostok,Venecia,Verona,Varadero,Veracruz,Valladolid,Vitoria,Uppsala,Utrecht,Ulsan,Oxford,Oslo,Orán,Odesa,Kingston,Kiev,Kioto,Kansas,Kabul,Jaipur,Jeddah,Ibiza,Innsbruck,Inca,Zacatecas,Zagreb,Zúrich,Yokohama,Yakutsk,Quebec,Querétaro,Quillabamba
`),
  marca: w(`
Adidas,Nike,Puma,Reebok,Fila,Converse,Vans,Under Armour,Apple,Samsung,Huawei,Xiaomi,Motorola,Nokia,Sony,LG,Lenovo,HP,Dell,Asus,Acer,Toshiba,Panasonic,Philips,Microsoft,Google,Amazon,Facebook,Meta,Instagram,WhatsApp,Netflix,Spotify,YouTube,TikTok,Twitter,Uber,Airbnb,Tesla,Toyota,Honda,Nissan,Hyundai,Kia,Ford,Chevrolet,Volkswagen,Audi,BMW,Mercedes,Mercedes-Benz,Ferrari,Lamborghini,Porsche,Renault,Peugeot,Fiat,Mazda,Subaru,Suzuki,Mitsubishi,Volvo,Jeep,Yamaha,Kawasaki,Ducati,Coca-Cola,Coca Cola,Pepsi,Fanta,Sprite,Inca Kola,Red Bull,Gatorade,Nestlé,Nescafé,Milo,Kellogg's,Danone,Gloria,Laive,Donofrio,D'Onofrio,Sublime,Field,Costeño,Alicorp,Primor,Bimbo,Oreo,Lays,Doritos,Pringles,Cheetos,McDonald's,KFC,Burger King,Starbucks,Subway,Pizza Hut,Domino's,Papa John's,Bembos,Norky's,Pardos,Zara,H&M,Mango,Gucci,Prada,Louis Vuitton,Chanel,Dior,Versace,Armani,Calvin Klein,Tommy Hilfiger,Lacoste,Levi's,Guess,Ray-Ban,Rolex,Casio,Swatch,Omega,Canon,Nikon,Kodak,GoPro,Lego,Mattel,Barbie,Hasbro,Nintendo,PlayStation,Xbox,Sega,Disney,Marvel,Warner,Colgate,Gillette,Dove,Nivea,Rexona,Axe,Pantene,Head & Shoulders,L'Oréal,Maybelline,Avon,Natura,Esika,Unique,Yanbal,Ripley,Saga Falabella,Falabella,Plaza Vea,Tottus,Metro,Wong,Sodimac,Promart,Oechsle,Walmart,Ikea,Bata,Totto,Faber-Castell,Faber Castell,Bic,Pilot,Stabilo,Artesco,Vinifan,Visa,Mastercard,PayPal,Yape,Plin,BCP,Interbank,BBVA,Scotiabank,Santander,Claro,Movistar,Entel,Bitel,Intel,AMD,Nvidia,Oracle,IBM,Cisco,Adobe,Zoom,Shell,Repsol,Primax,Pecsa,Kia,Quaker,Kinder,Knorr,Kotex,Kleenex,Jumbo,Jeep,JBL,Huggies,Pampers,Heinz,Hellmann's,Ideal,Inka Chips,Umbro,Uniqlo,Unilever,Gap,Tide,Ariel,Ace,Bolívar,Opal,Ola,Elite,Suave,Sapolio,Tramontina,Oster,Olympic,Rimac,Pacasmayo,Wilson,Wilkinson,Whirlpool,Xerox,Yahoo,Zoom,Zara,Volvo,Vicks,Valentino,Tic Tac,Twix,Snickers,M&M's,Milky Way,Mars,Ferrero,Nutella,Hershey's,Toblerone,Lindt,Cadbury,Sapporo,Pilsen,Cristal,Cusqueña,Corona,Heineken,Budweiser,Brahma,Quilmes
`),
  profesion: w(`
abogado,actor,actriz,administrador,agricultor,agrónomo,albañil,analista,antropólogo,arquitecto,artista,astronauta,astrónomo,auditor,azafata,bailarín,banquero,barbero,barista,biólogo,bombero,botánico,cajero,camarero,camionero,cantante,carnicero,carpintero,cartero,cerrajero,chef,chofer,científico,cirujano,cocinero,conductor,constructor,contador,costurera,dentista,diseñador,doctor,docente,ebanista,economista,editor,electricista,enfermero,enfermera,escritor,escultor,estilista,farmacéutico,filósofo,físico,florista,fontanero,fotógrafo,futbolista,ganadero,gasfitero,geógrafo,geólogo,gerente,guía,historiador,ingeniero,instructor,investigador,jardinero,joyero,juez,jugador,locutor,maestro,mecánico,médico,mesero,minero,modelo,músico,niñera,notario,nutricionista,obrero,odontólogo,oftalmólogo,panadero,paramédico,pastelero,peluquero,periodista,piloto,pintor,plomero,policía,político,profesor,programador,psicólogo,psiquiatra,químico,quiropráctico,radiólogo,recepcionista,relojero,reportero,sacerdote,sastre,secretario,secretaria,soldado,sociólogo,taxista,técnico,traductor,ujier,urólogo,vendedor,veterinario,vigilante,viticultor,zapatero,zoólogo,kinesiólogo,karateca,joyero,ilustrador,intérprete,herrero,higienista,granjero,guardia,detective,decorador,dibujante,electrónico,enólogo,economista,lavandera,librero,lechero,obstetra,ortodoncista,optometrista,youtuber,yesero,xilógrafo
`),
};

module.exports = { DICTIONARIES };
